lib/ae_canary_web/router.ex
defmodule AeCanaryWeb.Router do
  use AeCanaryWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Our pipeline implements "maybe" authenticated. We'll use the `:ensure_auth` below for when we need to make sure someone is logged in.
  pipeline :auth do
    plug AeCanaryWeb.Accounts.Pipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug AeCanaryWeb.Accounts.AddCurrentUser
  end

  pipeline :ensure_admin do
    plug AeCanaryWeb.Accounts.CheckAdmin
  end

  # Maybe logged in routes
  scope "/", AeCanaryWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout

    # Definitely logged in scope
    scope "/" do
      pipe_through [:ensure_auth]

      ## current user account management
      scope "/account" do
        get "/", UserController, :show_my
        get "/edit", UserController, :edit_my
        put "/", UserController, :update_my
        get "/password", UserController, :edit_my_password
        post "/password", UserController, :set_my_password
      end

      scope "/exchanges", Exchanges, as: :exchanges do
        get "/dashboard", ExchangeController, :dashboard
      end
    end

    # administrator pages
    scope "/" do
      pipe_through [:ensure_auth, :ensure_admin]

      ## user management
      resources "/users", UserController
      get "/users/:id/password", UserController, :edit_password
      post "/users/:id/password", UserController, :set_password

      scope "/exchanges", Exchanges, as: :exchanges do
        resources "/exchanges", ExchangeController
        resources "/addresses", AddressController
        get "/addresses/new/:exchange_id", AddressController, :new_by_exchange
      end

      scope "/tainted", TaintedAccounts, as: :tainted_accounts do
        resources "/accounts", AccountController
      end

      scope "/settings" do
        resources "/dashboard", DashboardController
        get "/dashboard/:id/toggle", DashboardController, :toggle_active
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", AeCanaryWeb do
  #   pipe_through :api
  # end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AeCanaryWeb.Telemetry
    end
  end
end

lib/ae_canary/accounts/user.ex
defmodule AeCanary.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Argon2

  schema "users" do
    field :email, :string
    field :password, :string, virtual: true
    field :pass_hash, :string
    field :name, :string
    field :comment, :string
    field :role, Ecto.Enum, values: [:admin, :user, :archived]
    field :email_big_deposits, :boolean, default: false
    field :email_boundaries, :boolean, default: false
    field :email_large_forks, :boolean, default: false
    field :email_idle, :boolean, default: false
    belongs_to :exchange_view, AeCanary.Exchanges.Exchange, references: :id

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [
      :email,
      :password,
      :pass_hash,
      :name,
      :role,
      :comment,
      :email_big_deposits,
      :email_boundaries,
      :email_large_forks,
      :email_idle,
      :exchange_view_id
    ])
    |> put_password_hash()
    ## |> put_exchange_view(attrs)
    |> validate_required([:email, :pass_hash, :name, :role])
    |> foreign_key_constraint(:exchanges, name: :users_exchange_view_id_fkey)
    |> unique_constraint(:email)
  end

  defp put_password_hash(
         %Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset
       ) do
    change(changeset, pass_hash: Argon2.hash_pwd_salt(password))
  end

  defp put_password_hash(changeset), do: changeset

  defp put_exchange_view(%Ecto.Changeset{valid?: true} = changeset, %{
         "exchange_view" => exchange_view
       }) do
    1 = put_assoc(changeset, :exchange_view, exchange_view)
  end

  defp put_exchange_view(changeset, _), do: changeset
end

lib/ae_canary_web/controllers/user_controller.ex
defmodule AeCanaryWeb.UserController do
  use AeCanaryWeb, :controller

  alias AeCanary.Accounts
  alias AeCanary.Accounts.User

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    null_val = Integer.to_string(AeCanaryWeb.UserView.all_exchanges_placeholder_value())

    user_params =
      case user_params do
        %{"exchange_view_id" => ^null_val} -> Map.put(user_params, "exchange_view_id", nil)
        _ -> user_params
      end

    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def show_my(conn, _) do
    user = current_user(conn)
    render(conn, "show.html", user: user, my_account: true)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def edit_my(conn, _) do
    user = current_user(conn)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset, my_account: true)
  end

  def update_my(conn, %{"user" => user_params}) do
    user = current_user(conn)

    sanitized_params =
      Map.take(user_params, [
        "name",
        "email",
        "email_boundaries",
        "email_big_deposits",
        "email_large_forks"
      ])

    case Accounts.update_user(user, sanitized_params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show_my))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset, my_account: true)
    end
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)
    null_val = Integer.to_string(AeCanaryWeb.UserView.all_exchanges_placeholder_value())

    user_params =
      case user_params do
        %{"exchange_view_id" => ^null_val} -> Map.put(user_params, "exchange_view_id", nil)
        _ -> user_params
      end

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end

  def edit_password(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "set_password.html", user: user, changeset: changeset)
  end

  def edit_my_password(conn, _) do
    user = current_user(conn)
    changeset = Accounts.change_user(user)
    render(conn, "set_password.html", user: user, changeset: changeset, my_account: true)
  end

  def set_password(conn, %{"id" => user_id, "user" => %{"password" => password}}) do
    user = Accounts.get_user!(user_id)

    case Accounts.update_user(user, %{password: password}) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "set_password.html", user: user, changeset: changeset)
    end
  end

  def set_my_password(conn, %{"user" => %{"password" => password}}) do
    user = current_user(conn)

    case Accounts.update_user(user, %{password: password}) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Your account had been updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show_my))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "set_password.html", user: user, changeset: changeset, my_account: true)
    end
  end

  defp current_user(conn) do
    Map.get(conn.assigns, :current_user)
  end
end

lib/ae_canary_web/views/user_view.ex
defmodule AeCanaryWeb.UserView do
  use AeCanaryWeb, :view

  alias AeCanary.Exchanges.Exchange

  def exchanges_dropdown_values() do
    AeCanary.Exchanges.list_exchanges()
    |> Enum.map(fn %Exchange{id: id, name: name} -> {name, id} end)
    |> Enum.into(%{})
    |> Map.put("__All exchanges", all_exchanges_placeholder_value())
  end

  def all_exchanges_placeholder_value, do: -1
end

lib/ae_canary_web/templates/user/edit.html.eex
<% my_account = if assigns[:my_account] do true else false end  %>
<%= if my_account do %>
<h4>Edit my account</h4>
<% else %>
<h4>Edit User</h4>
<% end %>

<% update_path = if my_account do Routes.user_path(@conn, :update_my) else Routes.user_path(@conn, :update, @user) end %>
<%= render "form.html", Map.put(assigns, :action, update_path) %>

<%= if my_account do %>
<div class="mt-3"><%= link "Back", to: Routes.user_path(@conn, :show_my) %></div>
<% else %>
<div class="mt-3"><%= link "Back", to: Routes.user_path(@conn, :index) %></div>
<% end %>

lib/ae_canary_web/templates/user/form.html.eex
<% my_account = if assigns[:my_account] do true else false end  %>
<div class="row g-3">
  <%= form_for @changeset, @action, fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <div class="row g-3 mb-3">
      <div class="col-sm-4">
        <%= label f, :email, class: "form-label" %>
        <%= email_input f, :email, class: "form-control", placeholder: "joe@doe.com", maxlength: 254 %>
        <%= error_tag f, :email %>
      </div>

      <div class="col-sm-4">
        <%= label f, :name, class: "form-label"  %>
        <%= text_input f, :name, class: "form-control", maxlength: 254 %>
        <%= error_tag f, :name %>
      </div>
      <%= if not my_account do %>
      <div class="col-sm-4">
        <% role = case @changeset.data.role do nil -> "user"; r -> r end %>
        <%= label f, :role, class: "form-label"  %>
        <%= select f, :role, ["Admin": "admin", "User": "user", "Archived user": "archived"], class: "form-select", selected: role %>
      </div>
      <div class="col-sm-4">
        <% exchange_view = case @changeset.data.exchange_view_id do nil -> all_exchanges_placeholder_value(); r -> r end %>
        <%= label f, :exchange_view_id, class: "form-label"  %>
        <%= select f, :exchange_view_id, exchanges_dropdown_values(), class: "form-select", selected: exchange_view %>
      </div>
      <% end %>
    </div>
    <%= if not my_account do %>
      <%= if assigns[:new_user] do %>
        <div class="row g-3 mb-3">
          <div class="col-sm-4">
            <%= label f, :password, class: "form-label" %>
            <%= password_input f, :password, class: "form-control", maxlength: 254 %>
            <%= error_tag f, :password %>
          </div>
        </div>
      <% end %>
    <% end %>


    <%= if not my_account do %>
      <div class="row g-3 mb-3">
        <div class="col-sm-12">
          <%= label f, :comment, "Comment (Optional, a maximum of 254 chars)", class: "form-label" %>
          <%= textarea f, :comment, class: "form-control", maxlength: 254 %>
          <%= error_tag f, :comment %>
        </div>
      </div>
    <% end %>

    <div class="row g-3 mb-3">
        <div class="form-label">Email Notification Preferences</div>
        <div class="col-sm-3">
            <%= label f, :email_big_deposits, "Large deposits", class: "form-label" %>
            <%= checkbox f, :email_big_deposits, class: "form-check-input" %>
            <%= error_tag f, :email_big_deposits %>
        </div>
        <div class="col-sm-3">
            <%= label f, :email_boundaries, "Boundary limits", class: "form-label" %>
            <%= checkbox f, :email_boundaries, class: "form-check-input" %>
            <%= error_tag f, :email_boundaries %>
        </div>
        <div class="col-sm-3">
            <%= label f, :email_large_forks, "Detected forks", class: "form-label" %>
            <%= checkbox f, :email_large_forks, class: "form-check-input" %>
            <%= error_tag f, :email_large_forks %>
        </div>
        <div class="col-sm-3">
            <%= label f, :email_idle, "Idle chain", class: "form-label" %>
            <%= checkbox f, :email_idle, class: "form-check-input" %>
            <%= error_tag f, :email_idle %>
        </div>

    </div>

    <div class="mb-3">
      <%= submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

lib/ae_canary_web/templates/user/index.html.eex
<h4>Listing Users</h4>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Role</th>
      <th>Comment</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <% max_comment_length = 30 %>
    <%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.name %></td>
      <td><%= user.role %></td>
      <td><%= String.slice(user.comment, 0, max_comment_length)%><%= if user.comment != nil and String.length(user.comment) > max_comment_length do %>...<% end %></td>

      <td>
        <span><%= link "Show", to: Routes.user_path(@conn, :show, user), class: "btn btn-light btn-sm" %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user), class: "btn btn-light btn-sm" %></span>
        <span><%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"],class: "btn btn-light btn-sm" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new), class: "btn btn-primary" %></span>

lib/ae_canary_web/templates/user/new.html.eex
<h4>New User</h4>

<%= render "form.html", Map.merge(assigns, %{action: Routes.user_path(@conn, :create),
                                             new_user: true}) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/ae_canary_web/templates/user/set_password.html.eex
<% my_account = if assigns[:my_account] do true else false end  %>
<%= if my_account do %>
<h4>Change my password</h4>
<p>This will set your password. You will have to use the new password from now on.</p>
<% else %>
<h4>Change a user's password</h4>
<p>This will set the password for user <span class="text-danger"><%= @user.name %></span><small> (<%= @user.email %>)</small>. That user will have to use the new password from now on.</p>
<% end %>

<% path = if my_account do Routes.user_path(@conn, :set_my_password) else Routes.user_path(@conn, :set_password, @user) end %>
<div class="row g-3">
  <%= form_for @changeset, path, [method: "post"], fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <div class="row g-3 mb-3">
      <div class="row g-3 mb-3">
        <div class="col-sm-4">
          <%= label f, :password, class: "form-label" %>
          <%= password_input f, :password, class: "form-control", maxlength: 254 %>
          <%= error_tag f, :password %>
        </div>
      </div>
    </div>
    <div class="mb-3">
      <%= submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<%= if my_account do %>
<span><%= link "Back", to: Routes.user_path(@conn, :show_my) %></span>
<% else %>
<span><%= link "Back", to: Routes.user_path(@conn, :show, @user) %></span>
<% end %>

lib/ae_canary_web/templates/user/show.html.eex
<% my_account = if assigns[:my_account] do true else false end  %>
<%= if my_account do %>
<h4>My account</h4>
<% else %>
<h4>Show User</h4>
<% end %>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Role:</strong>
    <%= @user.role %>
  </li>

  <%= if not my_account do %>
  <li>
    <strong>Comment:</strong>
    <%= @user.comment %>
  </li>
  <% end %>
  </ul>

<strong>Email Notification Preferences:</strong>
<ul>
  <li>
    <strong>Large deposits:</strong>
    <%= @user.email_big_deposits %>
  </li>

  <li>
    <strong>Exceeded boundaries:</strong>
    <%= @user.email_boundaries %>
  </li>

  <li>
    <strong>Detected forks:</strong>
    <%= @user.email_large_forks %>
  </li>

  <li>
    <strong>Idle chain:</strong>
    <%= @user.email_idle %>
  </li>

  <li>
    <strong>Specific exchange view:</strong>
    <%= if @user.exchange_view do %>
      <%= @user.exchange_view.name %>
    <% else %>
      none
    <% end %>
  </li>
</ul>
<%= if my_account do %>
<%= link "Edit", to: Routes.user_path(@conn, :edit_my), class: "btn btn-light" %>
<%= link "Change password", to: Routes.user_path(@conn, :edit_my_password), class: "btn btn-light" %>
<% else %>
<%= link "Edit", to: Routes.user_path(@conn, :edit, @user), class: "btn btn-light" %>
<%= link "Change password", to: Routes.user_path(@conn, :edit_password, @user), class: "btn btn-light" %>
<div class="mt-3"><%= link "Back", to: Routes.user_path(@conn, :index) %></div>
<% end %>