lib/ae_canary_web/router.ex
defmodule AeCanaryWeb.Router do
  use AeCanaryWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Our pipeline implements "maybe" authenticated. We'll use the `:ensure_auth` below for when we need to make sure someone is logged in.
  pipeline :auth do
    plug AeCanaryWeb.Accounts.Pipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug AeCanaryWeb.Accounts.AddCurrentUser
  end

  pipeline :ensure_admin do
    plug AeCanaryWeb.Accounts.CheckAdmin
  end

  # Maybe logged in routes
  scope "/", AeCanaryWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout

    # Definitely logged in scope
    scope "/" do
      pipe_through [:ensure_auth]

      ## current user account management
      scope "/account" do
        get "/", UserController, :show_my
        get "/edit", UserController, :edit_my
        put "/", UserController, :update_my
        get "/password", UserController, :edit_my_password
        post "/password", UserController, :set_my_password
      end

      scope "/exchanges", Exchanges, as: :exchanges do
        get "/dashboard", ExchangeController, :dashboard
      end
    end

    # administrator pages
    scope "/" do
      pipe_through [:ensure_auth, :ensure_admin]

      ## user management
      resources "/users", UserController
      get "/users/:id/password", UserController, :edit_password
      post "/users/:id/password", UserController, :set_password

      scope "/exchanges", Exchanges, as: :exchanges do
        resources "/exchanges", ExchangeController
        resources "/addresses", AddressController
        get "/addresses/new/:exchange_id", AddressController, :new_by_exchange
      end

      scope "/tainted", TaintedAccounts, as: :tainted_accounts do
        resources "/accounts", AccountController
      end

      scope "/settings" do
        resources "/dashboard", DashboardController
        get "/dashboard/:id/toggle", DashboardController, :toggle_active
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", AeCanaryWeb do
  #   pipe_through :api
  # end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AeCanaryWeb.Telemetry
    end
  end
end

lib/ae_canary_web/views/layout_view.ex
defmodule AeCanaryWeb.LayoutView do
  use AeCanaryWeb, :view
end

lib/ae_canary_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>AeCanary · Aeternity blockchain</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/chartjs-plugin-annotation.min.js") %>"></script>
    <script>
      const colorScheme = [
          "#25CCF7","#FD7272","#54a0ff","#00d2d3",
          "#1abc9c","#2ecc71","#3498db","#9b59b6","#34495e",
          "#16a085","#27ae60","#2980b9","#8e44ad","#2c3e50",
          "#f1c40f","#e67e22","#e74c3c","#ecf0f1","#95a5a6",
          "#f39c12","#d35400","#c0392b","#bdc3c7","#7f8c8d",
          "#55efc4","#81ecec","#74b9ff","#a29bfe","#dfe6e9",
          "#00b894","#00cec9","#0984e3","#6c5ce7","#ffeaa7",
          "#fab1a0","#ff7675","#fd79a8","#fdcb6e","#e17055",
          "#d63031","#feca57","#5f27cd","#54a0ff","#01a3a4"
      ];
    </script>
  </head>
  <body>
    <main>
      <div class="container py-3">
        <div class="py-2 border-bottom mb-3">
          <div class="d-flex flex-wrap justify-content-center">
            <div class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
              <h3><%= link "Ae Canary", to: Routes.page_path(@conn, :index), class: "text-dark text-decoration-none" %></h3>
            </div>
            <div class="text-end">
              <%= if  assigns[:current_user] do %>
                <div class="dropdown">
                  <button class="btn btn-light dropdown-toggle" type="button" id="accountDropdownMenu" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= @current_user.email %>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="accountDropdownMenu">
                    <li><%= link "My account", to: Routes.user_path(@conn, :show_my), class: "dropdown-item" %></li>
                    <%= if is_admin(@current_user) do %>
                      <li><%= link "All accounts", to: Routes.user_path(@conn, :index), class: "dropdown-item" %></li>
                    <% end %>
                    <%= if is_admin(@current_user) do %>
                      <li><%= link "Dashboard messages", to: Routes.dashboard_path(@conn, :index), class: "dropdown-item" %></li>
                    <% end %>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link "Log out", to: Routes.session_path(@conn, :logout), class: "dropdown-item" %></li>
                  </ul>
                </div>
              <% else %>
                <%= link "Login", to: Routes.session_path(@conn, :new), class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <%
            info = get_flash(@conn, :info)
            error = get_flash(@conn, :error)
            %>
            <%= if info do %>
              <div class="alert alert-info" role="alert"><%= info %></div>
            <% end %>
            <%= if error do %>
              <div class="alert alert-danger" role="alert"><%= error %></div>
            <% end %>
          </div>
        </div>
        <%= @inner_content %>
      </div>
    </main>

    <div class="container py-3">
      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-6 col-md">
            <h5>AeCanary</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://github.com/aeternity/ae_canary">GitHub repo</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://github.com/aeternity/ae_canary/commit/<%= AeCanary.Application.build() %>">Build: <%= AeCanary.Application.build() |> String.split_at(7) |> elem(0) %></a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About Aeternity</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://aeternity.com">Aeternity</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://www.aeternity-foundation.org">Aeternity Crypto Foundation</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://forum.aeternity.com">Official forum</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Explorers</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://explorer.mainnet.aeternity.io">MDW based explorer</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://www.aeknow.org">AEKnow</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>